### ISSUE TITLE
Table view frame accessed from background thread

### ISSUE THREAD

**Issue by stevenwenxu** [Shopify/FunctionalTableData#113]
`tableView.frame` is accessed directly in the `BlockOperation`, this is caught by the main thread checker.

<img width="1179" alt="screen shot 2018-10-09 at 1 32 06 pm" src="https://user-images.githubusercontent.com/3827809/46687940-263a7e00-cbca-11e8-9bbf-209b020a7a69.png">

**Comment by dannbeaus** [comment]
do you have your stack trace available?
how did you reproduce in your scenario?

**Comment by stevenwenxu** [comment]
It is a crash in POS where we have multiple rows with the same keys. However this isn't specific to any case because by looking at the code, the failure block is always run in the `blockOperation` which is on the `renderAndDiffQueue`.
