### ISSUE TITLE
Issues with using FunctionalTableData 

### ISSUE THREAD

**Issue by cesaredecal** [Shopify/FunctionalTableData#122]
Hey there, I'm trying to get my hands on this library but I'm having issues with using it. I installed FunctionalTableData through Carthage and then copied the sample classes (table view controller and label cell) to the newly project I've created. However, after running the project and tapping the plus button to add a new table view entry a crash occurs.

Specifically, it looks like there are some issues in the `TableSectionChangeSet` file. I couldn't specifically track down what is going on, but here is the sample project I am using (https://github.com/cesaredecal/ShopifyFunctionalTableDataIssue). This issue is occurring on every single Xcode project I test this library on. Maybe there's something wrong with my Carthage configuration or something else in general. Happy to provide more info if necessary.

I've also tried to install this library the other way, by simply dragging and dropping the FunctionalTableData folder into the project. However this leads to conflicts on my end (duplicate info.plist files and so on...). So I'm not really sure what to do at this point.

Thanks for your help!

**Comment by raulriera** [comment]
Hi,

I am able to compile and hit the + button in your project. Can you provide the error message you are seeing?

<img width="1853" alt="screen shot 2018-12-10 at 12 57 41 pm" src="https://user-images.githubusercontent.com/24159/49751400-498db200-fc7b-11e8-9f62-72bf392b5e4a.png">

**Comment by cesaredecal** [comment]
Glad to see it's working fine on your end. I am not seeing any error message (just "lldb"), however here is a screenshot:

![](https://i.imgur.com/YESIPrt.png)

I should say I'm running Xcode 10.0 beta which is probably why this is happening. Unfortunately Xcode 10.1 unexpectedly quits after trying to open any project.

**Comment by raulriera** [comment]
It seems to be something specifically to your environment, my screenshot was from Xcode 10.1

**Comment by cesaredecal** [comment]
Agreed, closing for now until I test the project with the latest Xcode. Thanks

**Comment by cesaredecal** [comment]
Update: it works great on Xcode 10.1, thanks!

**Comment by raulriera** [comment]
Glad you sort it out 🙂 let us know if you have any more questions about the library
