### ISSUE TITLE
Usage with Xib

### ISSUE THREAD

**Issue by dfairaizl** [Shopify/FunctionalTableData#131]
Hello!

Thank you for contributing this to the community! I am trying it out and am having a hard time understanding how to create `HostCell` cells who's view comes from a nib. I don't see any way that tableview's `register(_ nib: UINib?, forCellReuseIdentifier identifier: String)` method can work and I've tried to have the views instantiated by HostCell load nibs in their initializers and ran into some issues there too.

Do you have a best practice for doing this with your framework?

Thanks!
Dan

**Comment by raulriera** [comment]
Hey Dan,

A HostCell's view is at the end of a the a UIView itself, you could create a UIView that loads the xib file containing your code into it

Hope that helps, if not let us know

**Comment by dfairaizl** [comment]
Hi Raul,

Thanks for getting back to me so fast. I can get it working with something like the following but that still has some issues.

```swift
let section = TableSection(key: "section-1", rows: [
    DetailCellType(key: "row-1", state: item) { (view, state) in
        let cell: ItemListingDetails = .fromNib()
        view.addSubview(cell)
        
       // constraint stuff
        
        cell.configure(with: state)
    }
] as [CellConfigType])

tableData.renderAndDiff([section])
```

This is naive but it immediately causes problems like needing to not re-add the nib loaded view to the cell view etc. 

If you know of another direction please let me know!

**Comment by raulriera** [comment]
Hi,

I was thinking something more in the line of

```swift
class ContainerView: UIView {
  init() {
     .. load your nib and add it as a subView
  }
}
```

And then use the ContainerView in your HostCells. You are correct about the problem in the previous message, the cellUpdater `{ (view, state) in` is only meant for changing the properties using the state, not to add or remove anything from the view itself :)

**Comment by dfairaizl** [comment]
Ah yep that did the trick - it all makes sense now :-) Any interest in having this documented somewhere? I know its technically out of scope of this project but I imagine this is a common thing.
