### ISSUE TITLE
Touches cancelled when long pressed

### ISSUE THREAD

**Issue by raulriera** [Shopify/FunctionalTableData#166]
## What

When long pressing on a UICollectionViewCell using FunctionalCollectionData, the touch will be cancelled. Unlike its UITableViewCell counterpart.

To reproduce, create a FCD cell that has a selectionColor and selectionAction. Long press on it and then release, the selection closure won't fire and the color will revert back before releasing

**Comment by g-Off** [comment]
@raulriera did you determine if this was `FunctionalCollectionData` specific or standard behaviour of a `UICollectionView`?

**Comment by raulriera** [comment]
I did not 😬
