### ISSUE TITLE
Include the closure-based addTarget code

### ISSUE THREAD

**Issue by boourns** [Shopify/FunctionalTableData#77]
It's tough to use the vanilla addTarget(selector:) when you've got a table that includes a list of UI elements that are backed by some list of objects, and want to know which item in the list was interacted with.  The closure-based addTarget makes it easy because you can capture the data item currently being interacted with (and the view controller itself to trigger a re-render).

So in my naive and humble opinion the closure-based addTarget should come with FTD.

Also, hi :)

**Comment by raulriera** [comment]
👋 hi!

I ran into this same issue, I ended up using https://github.com/ActionKit/ActionKit to add support for closures in UIControls (Since they are a lot of them and I wanted to have support for older iOS versions).

**Comment by boourns** [comment]
ah that works, thanks Raul! <3
